BOOTSTRAP_SERVER: 192.168.29.247:9092
KAFKA_MAX_POLL_RECORD: 1000
KAFKA_CONSUMER_GROUP_ID: booking-consumer-test
KAFKA_SERVICE_TOPIC_NAME: booking_core_service_topic
KAFKA_STATE_MACHINE_TOPIC_NAME: state_machine_topic
KAFKA_CAMEL_TOPIC_NAME: apache_camel


camel:
  springboot:
    main-run-controller: true

server:
  port: 9090


app:
  camel-from: 'kafka:${KAFKA_CAMEL_TOPIC_NAME}?brokers=${BOOTSTRAP_SERVER}&maxPollRecords=${KAFKA_MAX_POLL_RECORD}&groupId=${KAFKA_CONSUMER_GROUP_ID}'
  camel-to-core-service: 'kafka:${KAFKA_SERVICE_TOPIC_NAME}?brokers=${BOOTSTRAP_SERVER}'
  camel-to-state-machine: 'kafka:${KAFKA_STATE_MACHINE_TOPIC_NAME}?brokers=${BOOTSTRAP_SERVER}'
